## Introduction to Numpy library
The Numpy library is an efficient interface to load, armazenate an manipulate data.
The concept of the library is using vectors and matrices of numbers to calculate your variables.

``` Python
    import numpy as np
    np.__version__ #to see what version of the library you are using.
    np.<TAB> # Inspect all numpy methods.
    np? #load documentation
 ```   

In [1]:
import numpy as np

In [3]:
np.__version__

'1.17.3'

**Matrices/ arrays**
The arrays in Numpy must be of a single type of variable contained. If not specified, and if multiple variable types are identified, Numpy converts them to the same type of other variables, when possible. The `dtype` parameter allows you to indicate your array type.

In [5]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([1, 2, 3 , 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**Creating arrays**

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((7, 7 ), 26)

array([[26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26],
       [26, 26, 26, 26, 26, 26, 26]])

In [15]:
# Array from 0 to 20, two by two.
np.arange(0, 22, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
np.arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

In [20]:
np.linspace(0, 1, 5) #5 numbers proportionally spaced ranging from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(0,15, 6)

array([ 0.,  3.,  6.,  9., 12., 15.])

**Random generated arrays**

In [25]:
np.random.random((3,3))

array([[0.77906636, 0.24471559, 0.75348718],
       [0.91763933, 0.60425136, 0.08389513],
       [0.22495   , 0.51199854, 0.9627176 ]])

In [28]:
np.random.normal(0, 1, (3,3)) # "0" being the mean value and 1 the standart deviation set.

array([[ 1.19786482, -1.24971789, -1.0628691 ],
       [ 1.58909948, -0.98667665, -0.00727704],
       [-0.50294838, -1.09605422,  0.48807891]])

In [34]:
np.random.randint(0, 10, (3,3,3))

array([[[6, 8, 2],
        [5, 1, 7],
        [1, 0, 1]],

       [[8, 4, 8],
        [3, 3, 4],
        [1, 2, 5]],

       [[8, 6, 1],
        [7, 3, 6],
        [3, 3, 5]]])

In [36]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array attributes
The matricial arrays basically have three main atributes:

 - `ndim`, number of dimensions of matrix
 - `shape`, size of matrix, `size` array's "total size"
 - `dtype` array's type of variable.
 
 

In [43]:
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [49]:
print("x1's dimension:",x1.ndim)
print("x1's size:", x1.shape)
print("x1's type:", x1.dtype)
print(x1)


x1's dimension: 1
x1's size: (6,)
x1's type: int64
[5 0 3 3 7 9]


In [50]:
print("x2's dimension:",x2.ndim)
print("x2's size:", x2.shape)
print("x2's type:", x2.dtype)
print(x2)

x2's dimension: 2
x2's size: (3, 4)
x2's type: int64
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [51]:
print("x3's dimension:",x3.ndim)
print("x3's size:", x3.shape)
print("x3's total size:", x3.size)
print("x3's type:", x3.dtype)
print(x3)

x3's dimension: 3
x3's size: (3, 4, 5)
x3's total size: 60
x3's type: int64
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [52]:
print("item size:", x3.itemsize, "bytes")
print("number of bytes:", x3.nbytes, "bytes")

item size: 8 bytes
number of bytes: 480 bytes


**Indexation of the arrays**


One-dimensioned arrays are indexed similarly as lists.

In [53]:
print(x1)

[5 0 3 3 7 9]


In [54]:
x1[0]

5

In [55]:
x1[4]

7

In [56]:
x1[-1]

9

In [57]:
x1[-2]

7

Multidimensional indexes can be accessed through it's coordinate in the matrix:

In [59]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [61]:
x2[0, 3]

4

In [62]:
x2[2, 0]

1

In [63]:
x2[1, -1]

8

The values within an array can be modified especifying the indexes. And a new value of different type can change the array type.

In [70]:
x2[2,-1] = 12

In [71]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

In [73]:
x1[3]= 12
x1

array([ 5,  0,  3, 12,  7,  9])

**Acessing subarrays**

slicing syntax `:`

```python
  
   x[initial:end:jump]
    
```
when not specified, initial index = 0, end = arrays size, jump=one by one = 1

In [75]:
x4= np.arange(10)
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x4[:5] #(ranging from 0 to 5)

array([0, 1, 2, 3, 4])

In [78]:
x4[5:] #ranging from 5 onwards.

array([5, 6, 7, 8, 9])

In [80]:
x4[4:7]

array([4, 5, 6])

In [81]:
x4[::2]

array([0, 2, 4, 6, 8])

In [82]:
x4[1::2]

array([1, 3, 5, 7, 9])

In [84]:
#Inverting your array with jump = -1
x4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [93]:
x4[9::-3]

array([9, 6, 3, 0])

**Multi-dimensioned arrays** works the same way, utilizing indexes separated by commas.


In [94]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

In [97]:
x2[:2, :4]

array([[3, 5, 2, 4],
       [7, 6, 8, 8]])

In [98]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [99]:
print(x2[:, 0])

[3 7 1]


In [100]:
print(x2[0, :])

[3 5 2 4]


### Calculating with arrays

In [102]:
x = np.arange(6)
print ("x =", x)
print("x+5 = ", x+5)
print("x-5 = ", x-5)
print("x*2 = ", x*2)
print("x/2 = ", x/2)
print("-x = ", -x)
print("x² = ", x**2)


x = [0 1 2 3 4 5]
x+5 =  [ 5  6  7  8  9 10]
x-5 =  [-5 -4 -3 -2 -1  0]
x*2 =  [ 0  2  4  6  8 10]
x/2 =  [0.  0.5 1.  1.5 2.  2.5]
-x =  [ 0 -1 -2 -3 -4 -5]
x² =  [ 0  1  4  9 16 25]


In [106]:
-(0.5*x + 1) ** 2

array([ -1.  ,  -2.25,  -4.  ,  -6.25,  -9.  , -12.25])

In [107]:
# Operation by method
np.add(x, 7)

array([ 7,  8,  9, 10, 11, 12])

**Operator list**

 |Operator| Equiv. Function | Description |
 |--------|-----------------|-------------|
 | + | `np.add()`           | addition |
 | - |  `np.subtract()`    | subtraction |
 | - |  `np.negative()` | negation of a sentence |
 | * |  `np.multiply()` | multiplication |
 | / |  `np.divide()` | division |
 | // | `np.floor_divide()` | floor division |
 | ** | `np.power()` | exponential function |
 | % |  `np.mod` | remainder of division |
 ||