## Libraries


When you want to perform advanced tasks you can use the code available in libraries, previously developed with many functional properties.

**Built-in libraries**

 - math library. 
 
 Use `import` command to load the library

In [2]:
import math

In [3]:
x = 3


In [4]:
print ("e^x = e^3 = %f" %math.exp(x))

e^x = e^3 = 20.085537


In [8]:
print("log(x) = log(3) = %f" %math.log(x))

log(x) = log(3) = 1.098612


In [10]:
from math import exp


In [12]:
print(exp(x))

20.085536923187668


In [14]:
from math import * # "*" Means "all"

In [16]:
print(exp(x))
print(log(x))

20.085536923187668
1.0986122886681098


**External libraries**

In [19]:
!pip install numpy scipy pandas



Giving an easier name to your library:

In [34]:
import numpy as np


Using imported functions.

In [40]:
x = np.array ([[1,2,3],[4,5,6]], dtype=np.float)


In [41]:
print(x)
print(type(x))

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


`numpy.ndarray` is used as a matrix, for which you can check its dimensions using `variable.check`

The arrays conatains elements of the same type.

In [45]:
y = np.array([1, "yes"])
y

array(['1', 'yes'], dtype='<U21')

In [47]:
y[0], type(y[0])

('1', numpy.str_)

In [49]:
y_list = [1, "yes"]
y_list[0], type(y_list[0])

(1, int)

Importing libraries functionalities for manipulating numbers:

In [51]:
from scipy.stats import pearsonr, spearmanr

In [57]:

print(spearmanr(x[1, :], (x[0, :])))
print(pearsonr(x[1, :], (x[0, :])))

SpearmanrResult(correlation=1.0, pvalue=0.0)
(0.9999999999999998, 1.3415758552508151e-08)


In [54]:
import pandas as pd

In [58]:
x


array([[1., 2., 3.],
       [4., 5., 6.]])

Creating a data frame with your array, later importing it as a `.csv` file (with no indice for the lines)

In [60]:
x_df = pd.DataFrame(x)
x_df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [61]:
x_df.to_csv('tmp_pd.csv', index = False)

In [64]:
df = pd.read_csv("tmp_pd.csv")

In [67]:
df


0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## Introduction to Object-oriented programming

In [70]:
class Person:
    department = 'Pharmaceutical Sciences School'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_localization(self, new_local):
        self.local = new_local


In [73]:
person = Person()
person.set_name("Paulo")
person.set_localization("Araraquara")

In [77]:
print("{} lives in {} and works at the {}".format(person.name, person.local, person.department))

Paulo lives in Araraquara and works at the Pharmaceutical Sciences School
